# tombi: format.rules.table-keys-order.disabled = true
[workspace]
name = "etch"
version = "0.0.1"
description = "comptime regex by tagged DFA"
authors = [
  "fogsong233 <fogsong233@gmail.com>",
]
license = "Apache-2.0"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]

[target.linux-64.dependencies]
sysroot_linux-64 = "==2.17"
gcc = "==14.2.0"
gxx = "==14.2.0"

[target.osx-arm64.dependencies]
clang = "==20.1.8"
clangxx = "==20.1.8"
lld = "==20.1.8"
libcxx = "==20.1.8"
